services:
  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:v2.39.1
    ports:
      - "9090:9090"
    volumes:
      - ./priv/data/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.2.6
    volumes:
      - ./priv/data/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
        - tempo

  loki:
    image: grafana/loki:2.6.1
    ports:
     - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:1.5.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./priv/data/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http

volumes:
    postgres-data: {}
    grafana_data:
    prometheus_data:
